# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros

In [3]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [4]:
arr = np.full((10,),1)

#### Create an array of 10 fives

In [5]:
arr = np.full((10,),5)

#### Create an array of the integers from 10 to 50

In [9]:
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [11]:
arr = np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8



In [13]:
arr = np.arange(0,9,1)
arr = arr.reshape((3,3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [14]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [19]:
arr = np.random.random((1,))
print(arr)

[0.78422291]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [23]:
arr = np.random.randn(25)
print(arr)

[-2.09611312  1.36629801  0.59408529 -0.22913823 -0.58386507 -1.61703258
 -0.76394293 -0.4161519   1.92861632  1.24747789  0.0227229   1.31745636
 -0.29309591  0.48217672  0.70647218 -1.04266825  0.09422545  0.3852213
 -0.08095955 -2.09573509  0.96146596 -1.18219992  0.9609585  -1.12878711
  1.45474498]


#### Create the following matrix:

In [26]:
arr = np.arange(0.01,1.001,0.01)
arr = arr.reshape(10,10)
print(arr)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

1.   List item
2.   List item



In [32]:
l = (1-0)/21
arr = np.arange(0,1+l-0.0001,l)
print(arr)

[0.         0.04761905 0.0952381  0.14285714 0.19047619 0.23809524
 0.28571429 0.33333333 0.38095238 0.42857143 0.47619048 0.52380952
 0.57142857 0.61904762 0.66666667 0.71428571 0.76190476 0.80952381
 0.85714286 0.9047619  0.95238095 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [33]:
arr = np.arange(1,26,1)
arr = arr.reshape((5,5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [36]:
arr = np.arange(12,27,1)
arr = arr.reshape((3,5))
print(arr)

[[12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]]


In [37]:
print(20)

20


In [38]:
arr = np.array([[2],[7],[12]])
arr

array([[ 2],
       [ 7],
       [12]])

In [39]:
arr = np.arange(21,26,1)
arr

array([21, 22, 23, 24, 25])

In [40]:
arr = np.arange(16,26,1)
arr = arr.reshape(2,5)
arr

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [42]:
mat = np.array([[ 1, 2, 3, 4, 5], [ 6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])
mat1 = np.sum(mat)
mat1

325

#### Get the standard deviation of the values in mat

In [44]:
stdev = np.std(mat)
stdev

7.211102550927978

#### Get the sum of all the columns in mat

In [47]:
mat1 = np.sum(mat,0)
mat1

array([55, 60, 65, 70, 75])

# Great Job!