# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros

In [2]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [3]:
arr=np.ones(10)

#### Create an array of 10 fives

In [4]:
arr = np.array([5,5,5,5,5,5,5,5,5,5])

#### Create an array of the integers from 10 to 50

In [5]:
array = [i for i in range(10, 51)]

#### Create an array of all the even integers from 10 to 50

In [6]:
array = [i for i in range(10, 51, 2)]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
matrix = [[i for i in range(j,j+3)] for j in range(0, 9, 3)]
print(matrix)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


#### Create a 3x3 identity matrix

In [13]:
matrix = [[1 if i == j else 0 for j in range(3)] for i in range(3)]

#### Use NumPy to generate a random number between 0 and 1

In [15]:
number = np.random.rand()
number

0.8234043972507044

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [16]:
numbers = np.random.randn(25)
numbers

array([ 0.26837201,  1.18051547, -0.53959126, -0.47457977, -2.73412199,
       -0.33578673,  2.60051656, -0.62257229,  0.56952471,  0.62311112,
        1.1489235 , -1.76213038,  0.04217902, -0.30485397, -0.87222536,
        0.76398077,  1.12151055, -0.63451693,  0.93411352,  0.21350561,
        0.25645729, -0.68813641, -1.52153   , -0.18794177, -1.48828507])

#### Create the following matrix:

In [20]:
sequence = np.arange(0.01, 1.01, 0.01)
sequence

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [23]:
points = np.linspace(0, 1, 20)
points

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [24]:
matrix = np.arange(1, 26).reshape(5, 5)

print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [26]:
matrix[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

20

In [30]:
matrix[0:3,1]


array([ 2,  7, 12])

In [32]:
matrix[4,0:5]

array([21, 22, 23, 24, 25])

In [34]:
matrix[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [36]:
sum = np.sum(matrix)
sum

325

#### Get the standard deviation of the values in mat

In [38]:
std = np.std(matrix)
std

7.211102550927978

#### Get the sum of all the columns in mat

In [39]:
sums = np.sum(matrix, axis=0)
sums

array([55, 60, 65, 70, 75])

# Great Job!