# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 10 zeros

In [ ]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [ ]:
arr = np.array([1,1,1,1,1,1,1,1,1,1])

#### Create an array of 10 fives

In [ ]:
arr = np.array([5,5,5,5,5,5,5,5,5,5])

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [ ]:
arr = np.arange(10, 51)

#### Create an array of all the even integers from 10 to 50

In [ ]:
arr = np.arange(10, 51,2)

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])

#### Create a 3x3 identity matrix

In [ ]:
arr = np.array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
random_number = np.random.rand()

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
random_number = np.random.rand(25)

#### Create the following matrix:

In [ ]:
num= np.arange(0.01,1.01,0.01)
matrix = num.reshape(10,10)

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
num = np.linspace(0,1,20)

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:


result = arr[1, -1]
print(result)

20


In [ ]:



matrix = arr[[0, 1, 2], [0]]

print(matrix)

[12 17 22]


In [ ]:
matrix= arr[-1, :].tolist()
matrix.insert(0,21)

print(matrix)


[21, 22, 23, 24, 25]


In [ ]:
row1 = arr[1, :]
row2 = arr[2, :]
row1 = np.insert(row1, 0, 16)
row2 = np.insert(row2, 0, 21)

array = np.array([row1, row2])




print(array)

[[16 17 18 19 20]
 [21 22 23 24 25]]


### Now do the following

#### Get the sum of all the values in mat

In [ ]:
mat = np.array([[ 1, 2, 3, 4, 5], [ 6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])

sum_arr = np.sum(mat)
print(sum_arr)

325


#### Get the standard deviation of the values in mat

In [ ]:
std_deviation = np.std(mat)
print(std_deviation)

7.211102550927978


#### Get the sum of all the columns in mat

In [ ]:
sum_column = np.sum(mat,axis =0)
print(sum_column )

[55 60 65 70 75]


# Great Job!